name: TorchArrow Nightly Build and Test for Conda
on:
#  schedule:
#    - cron: "0 0 * * *"
  pull_request:
    branches:
      - main
      # For PR created by ghstack
      - gh/*/*/base

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:
    secrets:
      AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID:
        required: true
      AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY:
        required: true

jobs:
  linux-container:
    runs-on: ubuntu-latest
#    container: prestocpp/velox-velox-torcharrow:kpai-20220301
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Print CPU info
        run: |          
          cat /proc/cpuinfo          

      - name: Create Conda Env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: conda_build_env

      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Based on https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          echo "::set-output name=timestamp::$(/bin/date -u "+%Y%m%d-%H:%M:%S")"
        shell: bash

      - name: Load ccache files
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ubuntu-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
              ubuntu-ccache-      

      - name: Install dependencies with APT
        run: |
          sudo apt-get update
          sudo apt install -y g++ cmake ccache ninja-build checkinstall git \
          libssl-dev libboost-all-dev libdouble-conversion-dev libgoogle-glog-dev \
          libgflags-dev libevent-dev libre2-dev

      # Based on https://github.com/facebookincubator/velox/blob/99429407c3d524e07b32b8b19a03aa7382f819cf/.circleci/config.yml#L114-L116
      - name: Configure ccache
        run: |
          echo "$GITHUB_WORKSPACE"
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache_root ccache -sz -M 1G
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache ccache -sz -M 1G      

      - name: Build and install folly and fmt
        # sudo doesn't preserve environment vairable; set it after sudo: https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo/33183620#33183620
        run: |
          sudo CMAKE_C_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER_LAUNCHER=ccache CCACHE_DIR=$GITHUB_WORKSPACE/.ccache_root scripts/setup-ubuntu.sh

      - name: Conda Build
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          # source /opt/conda/etc/profile.d/conda.sh
          conda activate conda_build_env                    
          conda install -yq conda-build -c conda-forge          
          ./packaging/build_conda.sh

#      - name: Upload wheel to S3 Storage
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY }}
#          S3_PATH: "s3://pytorch/whl/nightly/"
#        run: |
#          source /opt/conda/etc/profile.d/conda.sh
#          conda activate env${{ matrix.python-version }}
#          pip install --user awscli
#          set -x
#          if [[ -z "${AWS_ACCESS_KEY_ID}" ]]; then
#            echo "AWS_ACCESS_KEY_ID is not set, exiting upload"
#            exit 1
#          fi
#          for pkg in fixed_dist/torcharrow*.whl; do
#              ~/.local/bin/aws s3 cp "$pkg" "$S3_PATH" --acl public-read
#          done

  macos-container:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Create Conda Env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: conda_build_env

      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Conda Build
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          conda activate conda_build_env
          conda install -yq conda-build -c conda-forge
          MACOSX_DEPLOYMENT_TARGET=10.15 ./csrc/velox/velox/scripts/setup-macos.sh
          ./packaging/build_conda.sh

#      - name: Upload wheel to S3 Storage
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY }}
#          S3_PATH: "s3://pytorch/whl/nightly/"
#        run: |
#          pip install --user awscli
#          set -x
#          if [[ -z "${AWS_ACCESS_KEY_ID}" ]]; then
#             echo "AWS_ACCESS_KEY_ID is not set, exiting upload"
#             exit 1
#          fi
#          for pkg in fixed_dist/torcharrow*.whl; do
#              ~/.local/bin/aws s3 cp "$pkg" "$S3_PATH" --acl public-read
#          done
