name: Ubuntu Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      # For PR created by ghstack
      - gh/*/*/base

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print CPU info
        run: cat /proc/cpuinfo

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      # Based on https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          echo "::set-output name=timestamp::$(/bin/date -u "+%Y%m%d-%H:%M:%S")"
        shell: bash

      - name: Load ccache files
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ubuntu-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
              ubuntu-ccache-

      - name: Install dependencies with APT
        run: |
          sudo apt-get update
          sudo apt install -y g++ cmake ccache ninja-build checkinstall git \
          libssl-dev libboost-all-dev libdouble-conversion-dev libgoogle-glog-dev \
          libgflags-dev libevent-dev libre2-dev

      # Based on https://github.com/facebookincubator/velox/blob/99429407c3d524e07b32b8b19a03aa7382f819cf/.circleci/config.yml#L114-L116
      - name: Configure ccache
        run: |
          echo "$GITHUB_WORKSPACE"
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache_root ccache -sz -M 1G
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache ccache -sz -M 1G

      - name: Build and install folly and fmt
        # sudo doesn't preserve environment vairable; set it after sudo: https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo/33183620#33183620
        run: |
          sudo CMAKE_C_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER_LAUNCHER=ccache CCACHE_DIR=$GITHUB_WORKSPACE/.ccache_root scripts/setup-ubuntu.sh

      - name: Bulid TorchArrow
        run: |
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache ccache -sz
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache python setup.py develop --user

      - name: Install dependencies for test
        run: |
          pip3 install pytest  --user
          pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu/torch_stable.html --user

      - name : Run TorchArrow unit tests
        run: pytest --no-header -v torcharrow/test

      - name : Install TorchArrow
        run: |
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache python setup.py install --user
        
      - name: Build the docs
        run: |
          cd ./docs
          pip3 install -r requirements.txt --user
          make html 
          cd ..      
